export default [
  [
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
  ],
  [
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
  ],
  [
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
  ],
  [
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    {
      headlineOfQuestion: "aboba",
      answer1: "aboba",
      answer2: "aboba",
      answer3: "aboba",
      answer4: "aboba",
      rightAnswer: 'aboba1',
    },
    ,
  ],
];