export default [
    [{
        headlineOfQuestion: "Скільки  в javaScript типів примітивів ?",
        answer1: "2",
            answer2: "3",
            answer3: "6",
            answer4: "5",
            rightAnswer: '4',
        },
        {
            headlineOfQuestion: "Що таке масив?",
            answer1: "функція",
            answer2: " колекція з проіндексованими значеннями",
            answer3: "об'єкт",
            answer4: "область видимості",
            rightAnswer: '2',
        },
        {
            headlineOfQuestion: "У чому відмінність між локальної та глобальної змінної?",
            answer1: "Локальні помітні всюди, глобальні тільки у функціях",
            answer2: "Локальні можна перевизначати, глобальні не можна",
            answer3: "Глобальні помітні всюди, локальні тільки у функціях",
            answer4: "відмінностей немає",
            rightAnswer: '3',
        },
        {
            headlineOfQuestion: "Індексація масиву починається з ",
            answer1: "0",
            answer2: "1",
            answer3: "2",
            answer4: "-1",
            rightAnswer: '1',
        },
        {
            headlineOfQuestion: "Ключі властивостей це завжди...",
            answer1: "число",
            answer2: "рядок",
            answer3: "буль",
            answer4: "довільний тип",
            rightAnswer: '2',
        },
        {
            headlineOfQuestion: "Який цикл використовується для перебору властивостей об'єкта?",
            answer1: "for...each",
            answer2: "for...off",
            answer3: "for...in",
            answer4: "for...out",
            rightAnswer: '3',
        },
        {
            headlineOfQuestion: "Які аргументи приймає метод apply ()?",
            answer1: "Об'єкт і список аргументів для функції",
            answer2: "Об'єкт і масив аргументів для функції",
            answer3: "Список аргументів для функції",
            answer4: "Об'єкт",
            rightAnswer: '2',
        },
        {
            headlineOfQuestion: "Значення якої змінної не можна змінити після її оголошення?",
            answer1: "const",
            answer2: "let",
            answer3: "var",
            answer4: "constanta",
            rightAnswer: '1',
        },
        {
            headlineOfQuestion: "Який call метод приймає в якості аргументів?",
            answer1: "об'єкт",
            answer2: "список аргументів для функції",
            answer3: "об'єкт і масив аргуменів для функції",
            answer4: "об'єкт і список аргументів для функції",
            rightAnswer: '4',
        },
        {
            headlineOfQuestion: "Що таке arguments в тілі функції?",
            answer1: "Локальна змінна містить псевдомасив аргументів",
            answer2: "Локальна змінна містить псевдомасив параметрів",
            answer3: "Локальна змінна містить масив параметрів",
            answer4: "Локальна змінна містить масив аргументів",
            rightAnswer: '1',
        },
    ],
    [{
            headlineOfQuestion: "Яка властивість задає відступ для елемента?",
            answer1: "padding",
            answer2: "border",
            answer3: "margin",
            answer4: "width",
            rightAnswer: '3',
        },
        {
            headlineOfQuestion: "Виберіть значення rgb, яке відповідає зеленому кольору",
            answer1: "rgb(0,255,0)",
            answer2: "rgb(0,0,255)",
            answer3: "rgb(255,0,0)",
            answer4: "rgb(255,0,255)",
            rightAnswer: '1',
        },
        {
            headlineOfQuestion: "Що робить flex-wrap..",
            answer1: "задає перенесення елементів вздовж допоміжної осі",
            answer2: "задає перенесення елементів вздовж головної осі",
            answer3: "задає напрямок головної осі",
            answer4: "задає правило вирівнювання елементів вздовж головної осі",
            rightAnswer: '2',
        },
        {
            headlineOfQuestion: "Що змінює правила розрахунку розмірів content-area?",
            answer1: "display: inline-block",
            answer2: "display: block",
            answer3: "box-sizing: content-box/border-box",
            answer4: "display: inline",
            rightAnswer: '3',
        },
        {
            headlineOfQuestion: "Скільки осей є у flex контейнері?",
            answer1: "1",
            answer2: "3",
            answer3: "2",
            answer4: "у flex контейнері немає осей",
            rightAnswer: '3',
        },
        {
            headlineOfQuestion: "Який із типів селекторів має найбільший проіритет?",
            answer1: "тег",
            answer2: "ідентифікатор",
            answer3: "клас",
            answer4: "селектор атрибута",
            rightAnswer: '2',
        },
        {
            headlineOfQuestion: "Властивість position:relative змістить сусідній елемент при значенні властивості",
            answer1: "top: 50px;",
            answer2: "left: 50px;",
            answer3: "bottom: 50px;",
            answer4: "margin: 50px;",
            rightAnswer: '4',
        },
        {
            headlineOfQuestion: "Яке значення властивості transform відповідає за поворот елемента?",
            answer1: "scale",
            answer2: "rotate",
            answer3: "skew",
            answer4: "translate",
            rightAnswer: '2',
        },
        {
            headlineOfQuestion: "Виберіть правильне значення властивоті color",
            answer1: "#25fh17;",
            answer2: "rgba(250,50,1,37%);",
            answer3: "#110000",
            answer4: "hsla(100%,50%,25%,.1);",
            rightAnswer: '3',
        },
        {
            headlineOfQuestion: "Властивість position:fixed застосовують для",
            answer1: "створення випадаючого меню",
            answer2: "навігації всередині заданого блоку сторінки",
            answer3: "створення блоку, закріпленого у viewport",
            answer4: "навігації між сторінками",
            rightAnswer: '3',
        },
    ],
    [{
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
    ],
    [{
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        }, ,
    ],
];