export default [
    [{
        headlineOfQuestion: "Скільки  в javaScript типів примітивів ?",
        answer1: "2",
            answer2: "3",
            answer3: "6",
            answer4: "5",
            rightAnswer: '4',
        },
        {
            headlineOfQuestion: "Що таке масив?",
            answer1: "функція",
            answer2: " колекція з проіндексованими значеннями",
            answer3: "об'єкт",
            answer4: "область видимості",
            rightAnswer: '2',
        },
        {
            headlineOfQuestion: "У чому відмінність між локальної та глобальної змінної?",
            answer1: "Локальні помітні всюди, глобальні тільки у функціях",
            answer2: "Локальні можна перевизначати, глобальні не можна",
            answer3: "Глобальні помітні всюди, локальні тільки у функціях",
            answer4: "відмінностей немає",
            rightAnswer: '3',
        },
        {
            headlineOfQuestion: "Індексація масиву починається з ",
            answer1: "0",
            answer2: "1",
            answer3: "2",
            answer4: "-1",
            rightAnswer: '1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
    ],
    [{
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
    ],
    [{
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
    ],
    [{
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        },
        {
            headlineOfQuestion: "aboba",
            answer1: "aboba",
            answer2: "aboba",
            answer3: "aboba",
            answer4: "aboba",
            rightAnswer: 'aboba1',
        }, ,
    ],
];